### ISSUE TITLE
运行TF版本的模型，提示python停止工作

### ISSUE THREAD

**Issue by Gemini77** [ymcui/Chinese-ELECTRA#35]
没有GPU，每次运行时python就会提示停止工作
D:\paper\electra>python run_finetuning.py --data-dir \train --model-name electra
_small --hparams lcqmc.json
2020-06-28 19:51:11.486608: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64
_100.dll not found
2020-06-28 19:51:11.496134: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From D:\paper\electra\model\optimization.py:70: The name tf.t
rain.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

**Comment by ymcui** [comment]
麻烦你自行讲错误信息到搜索引擎里去寻找解决方案。

**Comment by ymcui** [comment]
windows下没有测试过，麻烦你自行到搜索引擎里搜索解决方案。
```
Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64
_100.dll not found
```

**Comment by Gemini77** [comment]
谢谢，已解决。
